# numpy 

# matrix

In [44]:
import numpy as np

In [45]:
a=np.matrix([[1,2],[3,4]])
b=np.matrix([[12,34],[34,3]])

In [46]:
a

matrix([[1, 2],
        [3, 4]])

In [47]:
b

matrix([[12, 34],
        [34,  3]])

In [48]:
#array multiplication
a*b

matrix([[ 80,  40],
        [172, 114]])

In [49]:
#matrix multiplication
a.dot(b)

matrix([[ 80,  40],
        [172, 114]])

In [50]:
#transpose 
c=np.array([[1,2,4],[3,4,3],[8,4,7]])
c

array([[1, 2, 4],
       [3, 4, 3],
       [8, 4, 7]])

In [51]:
np.transpose(c)

array([[1, 3, 8],
       [2, 4, 4],
       [4, 3, 7]])

In [52]:
c.T

array([[1, 3, 8],
       [2, 4, 4],
       [4, 3, 7]])

Dot and cross product with Matrix

In [53]:
A = [[1, 2, 3],[4, 5, 6],[1, 2, 3]]
 
B = [[1, 3, 5], [6, 5, 4],[3, 2, 1]]

In [54]:
dotproduct = np.dot(A,B)
print("Dot product of two array is:", dotproduct)
 

Dot product of two array is: [[22 19 16]
 [52 49 46]
 [22 19 16]]


In [55]:
dotproduct = np.cross(A, B)
print("Cross product of two array is:", dotproduct)

Cross product of two array is: [[  1  -2   1]
 [-10  20 -10]
 [ -4   8  -4]]


# indexing

#indexing using double bracket notation

In [56]:
c

array([[1, 2, 4],
       [3, 4, 3],
       [8, 4, 7]])

In [57]:
c[0][1]

2

In [58]:
c[1][1]

4

#indexing using single bracket notation

In [59]:
c[0,1]

2

# slicing

In [60]:
#[[1,2]
#[3,4]]
c[:2,:2]

array([[1, 2],
       [3, 4]])

In [21]:
#[[4, 3],
#[ 4, 7]]
c[1:,1:]

array([[4, 3],
       [4, 7]])

In [22]:
np.random.seed(12345)
d=np.random.randint(1,102,25).reshape(5,5)
d

array([[99, 30,  2, 37, 42],
       [35, 30,  2, 60, 15],
       [92, 81, 74, 12, 78],
       [11, 82, 83, 39,  8],
       [44, 24, 30, 57, 56]])

In [23]:
d[1:4,1:4]

array([[30,  2, 60],
       [81, 74, 12],
       [82, 83, 39]])

In [24]:
d[2:,2:]

array([[74, 12, 78],
       [83, 39,  8],
       [30, 57, 56]])

# Broadcasting

In [25]:
a = np.array([13, 9, 59]) 
print(a)
b = 7
print(b)
c = a + b
print(c)

[13  9 59]
7
[20 16 66]


# Build in function for creating array : 


Diagonal

In [27]:

np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

 ones 

In [28]:
np.ones(8)

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [29]:
np.ones(8,dtype="int")

array([1, 1, 1, 1, 1, 1, 1, 1])

In [31]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

 Zeros

In [55]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [56]:
np.zeros(3,dtype="int")

array([0, 0, 0])

In [57]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [58]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [59]:
np.zeros(4,order="f")

array([0., 0., 0., 0.])

In [60]:
np.zeros((3,4),order="f")

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# Built in method

squareroot

In [40]:
a=np.matrix([[1,2],[3,4]])

In [41]:
np.sqrt(a)

matrix([[1.        , 1.41421356],
        [1.73205081, 2.        ]])

Log

In [42]:
#Log (input) to the base e=(2.7)
arr=np.array([2,3,4,5,6])
log_value=np.log(arr) 
print(log_value)

[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


Exponential function 

In [61]:
 #e = 2.7182 (e^X and X=is the value pass by user) 
a = 1
b = np.exp(2)
print (np.log(a))
print (np.log(b))

0.0
2.0
