# numpy
The word NumPy stands for Numerical Python.
it is fundamental python package for scientific computing
it contains tools and technique to solve mathematical problems

# array
#All the elements in an array are of the same type.
#NumPy offers an array object called ndarray.
#it is  faster, more efficient, and require less syntax than standard python sequences.
#create array from list or tuples

In [31]:
import numpy as np

In [32]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr)

[1 2 3 4 5 6 7 8 9]


# indexing

In [33]:
arr[3]

4

In [34]:
arr[-5]

5

# slicing 
to retrive collection of values


In [35]:
arr[1:4]

array([2, 3, 4])

In [36]:
arr[1::3]

array([2, 5, 8])

In [37]:
print(type(arr))

<class 'numpy.ndarray'>


In [38]:
#0-D arrays
arr = np.array(42)
print(arr)


42


# 2-D array

In [39]:
arr = np.array([[1, 2,3], [4, 5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [40]:
#indexing
arr[0][0]

1

In [41]:
arr[1]

array([4, 5, 6])

In [42]:
#slicing
arr[1:,1:]

array([[5, 6]])

In [43]:
#it print entire array
arr[:,:]

array([[1, 2, 3],
       [4, 5, 6]])

# 3-D arrays 
it is 2-d array within array


In [44]:
arr = np.array([[[1, 2, 3], [4, 5, 6],[7, 8, 9]], [[4, 5, 6],[7, 8, 9], [10, 11, 12]]])
print(arr)


[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]


In [45]:
#indexing
arr[1][0][1]

5

In [46]:
arr[-2][-1][-1]

9

In [47]:
arr[1]

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [48]:
#slicing
arr[:,:,:1]

array([[[ 1],
        [ 4],
        [ 7]],

       [[ 4],
        [ 7],
        [10]]])

In [49]:
arr[:,1:,::1]

array([[[ 4,  5,  6],
        [ 7,  8,  9]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [50]:
#N-dimensions tells that how many dimensions the array have
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


# Broadcasting
It is method in numpy that allows to do arithmatic oprations on arrays of different size and shape
this is not apply on scalars
# Rules
#To check broadcast we need shape of array, dimension if dimension is not matched then need to add .
#The size of each dimension should be same.
#The size of one of the dimension should be equal to 1

In [51]:
a= np.array([1, 2, 3])
b= np.array([5, 6, 7, 8,9])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[1],[2],[3], [4]])



In [52]:
a.shape

(3,)

In [53]:
b.shape

(5,)

In [54]:
c.shape

(2, 3)

In [55]:
d.shape

(4, 1)

In [56]:
a+c

array([[2, 4, 6],
       [5, 7, 9]])

In [57]:
a+c

array([[2, 4, 6],
       [5, 7, 9]])

In [58]:
a+d

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6],
       [5, 6, 7]])